### ISSUE TITLE
Overkill perhaps?

### ISSUE THREAD

**Issue by commadelimited** [andrewpthorp/simple-http-server#2]
You can start a Python server (that serves the same purpose) from any directory on your machine with this shell function:

```
function server() {
    local port="${1:-8000}"
    open "http://localhost:${port}/"
    python -m SimpleHTTPServer "$port"
}
```

**Comment by jnewman** [comment]
@commadelimited There's a typo in SimpleHTTPServer.

**Comment by commadelimited** [comment]
Good catch @jnewman. Fixed.

**Comment by andrewpthorp** [comment]
Hey guys, one of the major reasons I did this was to get my feet wet with Node.js. This is most likely overkill, and definitely not ready for production, but if any of you guys are interested in working on the project / submitting pull requests to differentiate it and make it a useful tool, feel free!

**Comment by jnewman** [comment]
@andrewpthorp Yeah, I sorta figured. I'm writing a short article on building FE resources and want to keep my manually installed deps down to just Node. I'll be sure to add your point as a caveat. FWIW it's great for quick prototyping, which is all I've ever used the Python equivalent for anyways :-)

**Comment by OscarGodson** [comment]
Yeah, if you're on a *nix machine. This is really handy when working on windows for one.
