### ISSUE TITLE
Should serve index.html by default (or note that it doesn't)

### ISSUE THREAD

**Issue by jnewman** [andrewpthorp/simple-http-server#3]
I was making the switch and noticed this doesn't serve up index.html for a folder path by default. I've come to expect this behavior based on my experience w/ SimpleHTTPServer. Was just curious if this is an unimplemented feature, an oversight, or a good case for documenting the divergence.

**Comment by jcreamer898** [comment]
I'm pretty sure it already does this?

https://github.com/andrewpthorp/simple-http-server/blob/master/lib/server.js#L109

**Comment by andrewpthorp** [comment]
Yeah, sorry I completely missed this. I wrote this to serve up index.html by default. If there are any issues around it, I welcome pull requests to fix it!
