### ISSUE TITLE
Possibly have some kind of auth option?

### ISSUE THREAD

**Issue by jcreamer898** [andrewpthorp/simple-http-server#4]
This is just an idea, but I had a colleague ask about auth.

I sometimes open up a port since I have a static IP and show people work I'm doing all hosted with this lib.

It'd be a cool feature if you could do something like...

``` bash
nserver -p 8000 -auth s0m3p@ss
```

This might take you to some sort of intermediate page where you enter the password first before being allowed to view the page.

Let me know your thoughts and I can potentially help get it working...

Thanks!

**Comment by OscarGodson** [comment]
+1

**Comment by andrewpthorp** [comment]
Closing this as a duplicate of #5
